### PR TITLE
feat(multiApp): support handling multiple apps

### PR DESCRIPTION
**Pull request by christianalfoni**
BREAKING CHANGE:
Needs latest version of the debugger, 0.43 or higher

### CODE REVIEW

**Comment by Guria** [comment]
LGTM

**Comment by Guria** [comment]
Linting has failed. Also let's wait signal-store release first

**Comment by christianalfoni** [comment]
Yeah, I did a boo boo there, editing commit now and will test with new signal store first yes

**Comment by Guria** [comment]
LGTM

**Pull request merged**
